//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string marca { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<double> precio_compra { get; set; }
        public Nullable<double> precio_venta { get; set; }
        public Nullable<int> stock { get; set; }
    }
}
